-- Safe, repeatable starter content for the legacy T06 workspace.
-- Timestamps are generated by the database defaults. This seed deliberately
-- contains no execution_records and never sets a task status to done.

insert into public.workspaces (id, slug, title, timezone)
values (
  '10000000-0000-4000-8000-000000000001',
  'public',
  'Post-training Research Engineer 지원 준비',
  'Asia/Seoul'
)
on conflict (id) do update
set title = excluded.title,
    timezone = excluded.timezone;

insert into public.plans (
  id,
  workspace_id,
  title,
  start_date,
  end_date,
  priority,
  success_criteria,
  estimated_minutes
)
select
  '20000000-0000-4000-8000-000000000001',
  workspaces.id,
  'Post-training Research Engineer 지원 준비',
  date '2026-09-07',
  date '2026-10-07',
  1,
  '학습·실험·포트폴리오·코딩 테스트 준비 결과를 기록하고 부족한 역량을 다음 계획으로 연결한다.',
  1200
from public.workspaces
where id = '10000000-0000-4000-8000-000000000001'
on conflict (id) do nothing;

insert into public.tasks (
  id,
  plan_id,
  title,
  due_date,
  priority,
  tag,
  estimated_minutes
)
values
  ('30000000-0000-4000-8000-000000000001', '20000000-0000-4000-8000-000000000001', '공고의 필수·우대 역량 분해', null, 1, 'post-training', 0),
  ('30000000-0000-4000-8000-000000000002', '20000000-0000-4000-8000-000000000001', 'LLM/VLM fine-tuning 학습·실습', null, 1, 'post-training', 0),
  ('30000000-0000-4000-8000-000000000003', '20000000-0000-4000-8000-000000000001', '가설·실험·평가 결과 기록', null, 1, 'experiment', 0),
  ('30000000-0000-4000-8000-000000000004', '20000000-0000-4000-8000-000000000001', 'Agent Harness·데이터 합성 학습', null, 1, 'post-training', 0),
  ('30000000-0000-4000-8000-000000000005', '20000000-0000-4000-8000-000000000001', 'Foundation Model 트렌드 정리', null, 1, 'research', 0),
  ('30000000-0000-4000-8000-000000000006', '20000000-0000-4000-8000-000000000001', 'GitHub·포트폴리오 결과 정리', null, 1, 'portfolio', 0),
  ('30000000-0000-4000-8000-000000000007', '20000000-0000-4000-8000-000000000001', '알고리즘·딥러닝 코딩 테스트 준비', null, 1, 'coding-test', 0)
on conflict (id) do nothing;
